import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={inter.className}
        style={{
          background: "#fff",
          color: "#000",
          width: "100%",
          fontFamily: "Trebuchet MS (sans-serif)",
          font: "caption",
        }}
      >
        {children}
      </body>
    </html>
  );
}
